### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by skworden** [leandrogehlen/yii2-treegrid#1]
I'm having an issue with the grouping.  

One level deep nest / groups properly

If it's deeper than one level it isn't nesting the child elements under the proper parent attribute. However, the open and close toggle icon, opens and closes the correct elements event though they aren't in the right location on the grid.  I don't know if it's because the PK and Parent fields are strings and not integers.
![treegrid](https://cloud.githubusercontent.com/assets/2423551/9332072/e23987f4-4590-11e5-8aad-7379dccedcd6.jpg)

Here is my exact config

```
TreeGrid::widget([
        'dataProvider' => $dataProvider,
        'keyColumnName' => 'id',
        'parentColumnName' => 'p_id',
        'pluginOptions' => [
            'initialState' => 'collapsed',
            'saveState' => true,
            'saveStateName' => 'locations-list-state'
        ],
        'columns' => [
            'name',
            'id',
            'p_id'
        ],
    ]);

```

**Comment by leandrogehlen** [comment]
I believe that i had same problem.
You can try apply an order by `parent_location`

**Comment by skworden** [comment]
I have it sorting by the parent without any luck.  It looks like there are other people with the same issue. https://github.com/maxazan/jquery-treegrid/issues/15

**Comment by liyunfang** [comment]
@leandrogehlen   My PR forgot to change the readme.
