### ISSUE TITLE
multi levels won't work

### ISSUE THREAD

**Issue by rawad1** [leandrogehlen/yii2-treegrid#15]
I am trying to use the extension with multi-levels categories but it is only show two levels

**Comment by leandrogehlen** [comment]
I think, that is a configuration problem.
It's necessary more information

**Comment by rawad1** [comment]
I have table with these columns: category_id,  category_parent_id, .... 
And these are the configurations :
keyColumnName => category_id,
parentColumnName => category_parent_id,
parentRootValue => 0
Any thing wrong with it?

**Comment by leandrogehlen** [comment]
depends, the first record  `category_parent_id` has value 0?

**Comment by leandrogehlen** [comment]
I'm using the plugin and the community to
![example](https://user-images.githubusercontent.com/1750751/27346506-d803e0aa-55c3-11e7-804e-2c98ee962099.png)

**Comment by rawad1** [comment]
in category table the category that have no parent the category_parent_id = 0 
and this is the tree view that i have, there are sub-categories in Cars, Car Accessories , ..... but nothing is shown

![screen shot 2017-06-21 at 9 21 46 am](https://user-images.githubusercontent.com/17817327/27370072-70825498-5663-11e7-8a13-e3a512868c5e.png)

**Comment by leandrogehlen** [comment]
Can you send me a backup database from this table?

**Comment by rawad1** [comment]
this is the table that i am working on
[category.sql.zip](https://github.com/leandrogehlen/yii2-treegrid/files/1091112/category.sql.zip)

**Comment by rawad1** [comment]
hi, do we have any progress with my issue ???? 
thank you

**Comment by leandrogehlen** [comment]
I made a fix, i hope solve problem

**Comment by rawad1** [comment]
thank you for your time, i have tried the fix that you made but i still have the problem

**Comment by leandrogehlen** [comment]
the problem wasn't solved?

**Comment by rawad1** [comment]
no it still shows only two levels

**Comment by leandrogehlen** [comment]
I used your data to made the fix, and here is working

![test](https://user-images.githubusercontent.com/1750751/27540891-38fabba2-5a58-11e7-86c4-cfec7a0f9b02.png)

**Comment by rawad1** [comment]
i am using this config 
...
    'keyColumnName' => 'category_id',
    'parentColumnName' => 'category_parent_id',
    'parentRootValue' => '0', //first parentId value
    'pluginOptions' => [
        'initialState' => 'collapsed',
    ],
...

and i have this result
![screen shot 2017-06-26 at 4 26 29 pm](https://user-images.githubusercontent.com/17817327/27541344-4cab7a72-5a8c-11e7-86b7-2e0226d8e4fa.png)

and this is the inspect element screenshot for the data
![screen shot 2017-06-26 at 4 29 18 pm](https://user-images.githubusercontent.com/17817327/27541485-be313d94-5a8c-11e7-9057-b7c4b8f41cb7.png)

**Comment by leandrogehlen** [comment]
I think problem is your provider, i am using:

```php
public function actionIndex()
{
    $dataProvider = new ActiveDataProvider([
        'query' => Category::find(),
        'pagination' => false
    ]);

    return $this->render('index', [
        'dataProvider' => $dataProvider
    ]);
}
```

**Comment by rawad1** [comment]
thank you it works,
i forget to set 'pagination' => false in my dataprovider
thank you for your time ..
