### ISSUE TITLE
Search in view

### ISSUE THREAD

**Issue by Mandzuk** [leandrogehlen/yii2-treegrid#17]
Hi! Tell me please, How I can add filterModel and column`s filter? Example, in GridView
` 'filterModel' => $searchModel,`
for column: `[
                'attribute'=>'articles_id',
                'format' => 'html',
                'value' => function($data){
                    if (!empty ($data->article))
                        return $data->article->title;
                },
                'filter' => \common\models\ArticlesComments::getArticlesList()
            ],`

**Comment by leandrogehlen** [comment]
See #9
