### ISSUE TITLE
in PHP 7.2 Object  is a special class name

### ISSUE THREAD

**Issue by chstudio-mail-ru** [leandrogehlen/yii2-treegrid#22]
PHP 7.2
PHP Compile Error – yii\base\ErrorException
Cannot use yii\base\Object as Object because 'Object' is a special class name

**Comment by leandrogehlen** [comment]
But the extension don't use `Object`.
Probably your project uses lower version than 2.0.13

**Comment by rfcasallasm** [comment]
Your last version released (**1.0.1**) has the issue, but not your current code on github, I think you need to release a new version with last changes.

**Comment by leandrogehlen** [comment]
Ok, the new version has been relesead.
