### ISSUE TITLE
Loose comparison in normalizeData()

### ISSUE THREAD

**Issue by kochs-online** [leandrogehlen/yii2-treegrid#5]
When comparing parent IDs the function `normalizeData()` uses loose comparison:

``` php
if ($element[$this->parentColumnName] == $parentId) { [...] }
```

This can result in false positives (which ultimately can lead to recursive hierarchies, i.e. infinite loops during code execution).
Example:

``` php
$element[$this->parentColumnName] = 0;   // int(0)
$parentId = 'p1';   // string(2) "p1"
$element[$this->parentColumnName] == $parentId   // true
```

Using [strict comparison](https://php.net/manual/types.comparisons.php) will prevent this behaviour:

``` php
if ($element[$this->parentColumnName] === $parentId) { [...] }
```

Example:

``` php
$element[$this->parentColumnName] = 0;   // int(0)
$parentId = 'p1';   // string(2) "p1"
$element[$this->parentColumnName] === $parentId   // false
```

It cost me about four days to figure this out. D'oh! :persevere:

**Comment by abdulquddus** [comment]
@kochs-online When I follow your instructions it give me nothing. Secondly I have a table that is like 

id, name, parent_id

Id can be inserted in a parent_id if it is a child. Secondly my table has many IDS deleted in between. that makes it look worse and I am assuming this thing as a problem. I have many childs of 1 
![issue](https://cloud.githubusercontent.com/assets/11033422/13243814/84d389c0-da23-11e5-90a8-aeedca5af8ee.png)

here it shows nothing on one. same if many place I have more than two childs of a parent_id but showing no more than two. like I have 2 childs of 3 but here only 1 is displaying

**Comment by kochs-online** [comment]
@abdulquddus In that case I don't think this is related. Maybe it's best if you file another issue and give a minimal example dataset and your TreeGrid configuration to reproduce that kind of error.

**Comment by leandrogehlen** [comment]
@abdulquddus  you are right. I will fix.

**Comment by abdulquddus** [comment]
@leandrogehlen Thanks I am waiting for this fix.
